from models import State, Nfa, Edge, Result
from algorithms import ThompsonsConstructor, ShuntingYard

def match(infix, string):
    """
        Match string to infix reg ex
        @param infix - the infix regex match string against
        @string - string to be matched to infix regex
    """

    # get the postfix for the infix using ShuntingYard algorithm
    postfix = ShuntingYard.shunt(infix)
    # create a new ThompsonsConstructor using the postfix
    tc = ThompsonsConstructor(postfix)
    # get the NFA generated by the ThompsonsConstructor object
    nfa = tc.solutionNfa

	# set of current and next states
    currentStates, nextStates = set(), set()
	# add initial state of nfa to current states
    currentStates |= followEedges(nfa.initialState)

	# loop through each character in the string
    for s in string:
		# loop through current states
        for c in currentStates:
            # check if state is labelled s
            if(c.label == s):
				# follow its E edge (will only be one)
                nextStates |= followEedges(c.e1)
		# set current to next and clear next set
        currentStates = nextStates
        # reinitialise the set of next states
        nextStates = set()

    # was the string accepted?
    isAccepted = nfa.acceptState in currentStates
    # return a Result object
    return Result(string, infix, isAccepted, postfix, tc)


def followEedges(state):
	"""Returns the set of states that can be reached from
		the state, following the arrows"""

	# create a new set with state as its only member
	states = set()
	states.add(state)
	# if state has e arrows
	if(state.label is None):
		# check if edge one is a state
		if(state.e1 is not None):
			# recursively follow the edges
			# union states
			states |= followEedges(state.e1)
		# check if edge one is a state
		if(state.e2 is not None):
			# recursively follow the edges
			# union states
			states |= followEedges(state.e2)

	# return the set of states
	return states
